config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'home/transaction'
  devise_for :users

  root 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_paper_trail
  belongs_to :user

  def deposit(amount)
  	self.update(balance: balance + amount.to_i)
  end

  def withdrawl(amount)
  	self.update(balance: balance - amount.to_i)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :account
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_for_paper_trail
    logged_in? ? current_user.id : 'User'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	before_action :find_account
  def index
  end

  def transaction
  	if params[:commit] == "Deposit"
  		@account.deposit(params[:amount])
  	elsif params[:commit] == "Withdrawl"
  		@account.withdrawl(params[:amount])
  	end
  end

  private
  def find_account
  	@account = current_user.account || current_user.create_account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_enquiry.html.erb
<table>
  <tr><th> Total Available Balance </th></tr>
  <tr><td><%= current_user.account.balance%></td></tr>
</table>

app/views/home/index.html.erb
<%= form_tag home_transaction_path, remote: true do %>
  <div>
    <%= label_tag :amount %>
    <%= number_field_tag :amount, 0.0, required: true %>
  </div>
  <%= submit_tag 'Deposit' %>
  <%= submit_tag 'Withdrawl' %>
<% end %>

<br><br>
<div id = "balance"></div>

app/views/home/transaction.js.erb
$("#balance").html("<%= escape_javascript render(:partial => 'enquiry') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
<%= yield %>

</body>
</html>